name: Build and Push to Docker Hub

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push payment-services
        uses: docker/build-push-action@v5
        with:
          context: ./payment-services
          file: ./payment-services/Dockerfile
          push: true
          tags: your-dockerhub-username/user-

      - name: Build and Push order-services
        uses: docker/build-push-action@v5
        with:
          context: ./order-services
          file: ./order-services/Dockerfile
          push: true
          tags: your-dockerhub-username/order-

      - name: Build and Push menu-services
        uses: docker/build-push-action@v5
        with:
          context: ./menu-services
          file: ./menu-services/Dockerfile
          push: true
          tags: your-dockerhub-username/


      - name: Build and Push inventory-services
        uses: docker/build-push-action@v5
        with:
          context: ./inventory-services
          file: ./inventory-services/Dockerfile
          push: true
          tags: your-dockerhub-username/


         - name: Build and Push customer-services
        uses: docker/build-push-action@v5
        with:
          context: ./customer-services
          file: ./customer-services/Dockerfile
          push: true
          tags: your-dockerhub-username/

- name: Build and Push api-sgateway
        uses: docker/build-push-action@v5
        with:
          context: ./api-gateway
          file: ./api-gateway/Dockerfile
          push: true
          tags: your-dockerhub-username/
